name: Start Docker Environment
description: "Start docker-compose environment."

inputs:

  repository:
    description: 'Repository name with owner. For example, actions/checkout'
    required: true

  branch:
    description: 'Branch to push the changes.'
    required: true

  token:
    description: 'GitHub token to push the changes.'
    required: true

runs:
  using: "composite"

  steps:

    - name: Checkout Badges Repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}
        repository: ${{ inputs.repository }}
        path: '${{ inputs.repository }}'
        ref: ${{ inputs.branch }}

    - name: Create and commit file
      shell: bash
      run: |
        echo "Creating file"
        echo "test" > test.txt
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git add test.txt
        git commit -m "Add test.txt"
        git push
