name: Start Docker Environment
description: "Start docker-compose environment."

inputs:

  gist-id:
    description: 'Gist ID to store the badge.'
    required: true

  gist-secret:
    description: 'Gist secret to store the badge.'
    required: true

runs:
  using: "composite"

  steps:
    - name: Gen Full Coverage Json
      id: shield-coverage-data
      if: ${{ github.event_name == 'pull_request' && !cancelled() }}
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const summariesPath = 'build/reports/coverage-reports/full-coverage-aggregated-summary.json';
          const summariesRaw = fs.readFileSync(summariesPath, 'utf8');
          const summary = JSON.parse(summariesRaw);

          const linesCoverage = summary.coverageInfo
            .find(entityCoverage => entityCoverage.coverageEntity === 'LINE');

          const badgeData = {
            schemaVersion: 1,
            label: summary.view,
            "message": `${linesCoverage.percents}%`,
            "color": "green"
          };
          const badgeDataFile = `dc-${summary.view}-coverage.json`;
          fs.writeFileSync(badgeDataFile, JSON.stringify(badgeData, null, 2));
          core.setOutput('file', badgeDataFile);
          
          const badgeDataUrl = `https://gist.githubusercontent.com/SurpSG/${{ inputs.gist-id }}/raw/${badgeDataFile}`;
          const badgeUrl = `https://img.shields.io/endpoint?url=${badgeDataUrl}`
          core.summary.addRaw(`${badgeUrl}`).write();

    - name: Create Awesome Badge
      uses: schneegans/dynamic-badges-action@v1.7.0
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: ${{ vars.GIST_ID }}
        filename: ${{ steps.shield-coverage-data.outputs.file }}
        label: Coverage
        message: 70%
        color: orange
