name: Release plugin

on:
  workflow_dispatch:

jobs:

  create-release:
    runs-on: ubuntu-latest
    steps:

      - name: Clone project
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build artifacts
        run: ./gradlew assemble

      - name: Get version
        id: release_version
        run: |
          echo "version=$(grep 'version=' gradle.properties | cut -d '=' -f 2)" >> $GITHUB_OUTPUT

      - name: Create Github release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.release_version.outputs.version }}
          prerelease: true
          title: "Release ${{ steps.release_version.outputs.version }}"

      - name: Publish plugin
        run: ./gradlew publishPlugins -Pgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} -Pgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}

      - name: Create PR main to develop
        uses: repo-sync/pull-request@v2
        with:
          source_branch: 'main'
          destination_branch: 'develop'
          pr_title: 'Merge main to develop'
          github_token: ${{ secrets.GITHUB_TOKEN }}
