name: Build

on:
  push:
    branches:
      - '**'

jobs:

  build-and-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BADGES_APP_ID }}
          private-key: ${{ secrets.BADGES_APP_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Upload file
        id: upload-file
        uses: actions/upload-artifact@v4
        with:
          name: badges
          path: badges/**/*.svg

      - name: Call Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: update-badges.yaml
          ref: refs/heads/main
          token: ${{ steps.generate-token.outputs.token }}
          repo: '${{ github.repository_owner }}/coverage-badges'
          inputs: |
            {
              "target-repo": "${{ github.event.repository.name }}",
              "badges-artifact-id": "${{ steps.upload-file.outputs.artifact-id }}",
              "artifacts-source-run-id": "${{ github.run_id }}"
            }
